---
name: Check Compose

permissions:
  pull-requests: read
  contents: read

on:
  push:
    paths:
      - "releases/*.conf"
  pull_request:
    paths:
      - "releases/*.conf"

jobs:
  check-compose:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
    steps:
      - name: prepare env
        run: |
          dnf install -y --setopt=tsflags=nodocs git 'dnf-command(copr)' epel-release

      - name: enable repositories
        run: |
          dnf copr enable -y sbonazzo/EL8_collection

      - name: install deps
        run: |
          dnf install -y repoman

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Compose config files
        run: |
          mkdir -p compose-test
          for config_file in $(git show --pretty="format:" --name-only | grep -E "^releases/.*conf$")
          do
              if [[ -e "${config_file}" ]] ; then
                  if [[ "${config_file}" =~ "alpha" ]] || [[ "${config_file}" =~ "beta" ]]; then
                      # Not archiving composed repository to save time during 4.3 mass import
                      repoman compose-test add conf:"${config_file}"
                      echo "Skipping git hash test being pre-release compose"
                  else
                      repoman compose-test add conf:"${config_file}"
                      if [[ -n $(find compose-test -name "*.git*.rpm") ]] ; then
                          echo "RPMs with git hash in NVR are not allowed within releases" >&2
                          exit 1
                      fi
                  fi
              else
                  echo "Skipping ${config_file} since it has been removed."
              fi
          done
